[package]
name = "business_logic"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
thiserror = "1.0"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }

log = "0.4.27"

models = { path = "./../models" }
data_access = { path = "./../data_access"}