#!/bin/bash
set -e  # если какая-то команда аварийно завершится, скрипт тоже завершится

cd ./backend/api || exit 1

echo "=== FORMAT CHECK ==="
echo ""

make check-fmt
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo "ERROR: Code not formatted! Commit aborted."
  exit 1
else
  echo "Code formatting check passed."
fi

echo ""
echo "=== CYCLOMATIC CHECK ==="
echo ""

make check-cyclomatic
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo "ERROR: Code too cyclomatically complex! Commit aborted."
  exit 1
else
  echo "Cyclomatic complexity check passed."
fi

echo ""
echo "=== HALSTEAD CHECK ==="
echo ""

make check-halstead
RESULT=$?
if [ $RESULT -ne 0 ]; then
  echo "ERROR: Code too Halstead complex! Commit aborted."
  exit 1
else
  echo "Halstead complexity check passed."
fi

echo ""
echo "=== All pre-commit checks passed successfully!"
exit 0
