version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    
    ports:
      - "6379:6379"
    networks:
      - db

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ${PROJECT_ROOT}/db/data:/data
    networks:
      - db
  
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ${PROJECT_ROOT}/db/data:/data
      - ${PROJECT_ROOT}/db/sql_scripts/clickhouse:/scripts
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    networks:
      - db
  
  test-container:
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: test-container
    volumes:
      - "./allure-report:/app/api/allure-report"
  
  autotracker-api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: autotracker-api
    restart: always
    environment:
      - POSTGRES_ADDRESS=postgres
      - CLICKHOUSE_ADDRESS=clickhouse
      - REDIS_ADDRESS=redis
    ports:
      - "9090:9887"
    volumes:
      - "./logs:/app/logs"
    depends_on:
      - postgres
      - clickhouse
      - redis
    networks:
      - db

volumes:
  redis_data:
  postgres_data:
  clickhouse_data:

networks:
  db:
    driver: bridge