openapi: 3.1.0
info:
  title: AUTOTRACKER API
  description: API сервиса отслеживания маршрутов AutoTracker
  license:
    name: ''
  version: 0.2.0
servers:
  - url: http://127.0.0.1:9887
    description: Local server
  - url: http://{url}:9887
    description: Local network API
    variables:
      url:
        default: 0.0.0.0
        description: Default local network
paths:
  /api/v2/cars/route:
    post:
      tags:
        - route
        - car
      summary: Получение маршрута
      description: Получение маршрута по гос.номеру и дате
      operationId: handle_route_v2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouteRequest'
        required: true
      responses:
        '200':
          description: Маршрут успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RouteResponse'
        '400':
          description: Невалидные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '401':
          description: Пользователь не авторизирован
        '403':
          description: Недостаточно прав
        '404':
          description: Данные не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Внутренняя ошибка сервера
      security:
        - jwt_bearer_auth: []
  /api/v2/cars/search:
    post:
      tags:
        - search
        - car
      summary: Поиск автомобилей
      description: Поиск автомобилей по общим фильтрам
      operationId: handle_search_cars_by_filters_with_offset_v2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchCarsRequest'
        required: true
      responses:
        '200':
          description: Автомобили успешно найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarSearcherResponse'
        '400':
          description: Невалидные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '401':
          description: Пользователь не авторизирован
        '403':
          description: Недостаточно прав
        '500':
          description: Внутренняя ошибка сервера
      security:
        - jwt_bearer_auth: []
  /api/v2/track-infos/search:
    post:
      tags:
        - search
        - track-info
      summary: Поиск отслеживаний
      description: Поиск отслеживаний по общим фильтрам
      operationId: handle_search_track_info_by_filters_with_offset_v2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchTrackInfoByFilterRequest'
        required: true
      responses:
        '200':
          description: Информация об отслеживаниях успешно найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackInfoSearcherResponse'
        '400':
          description: Невалидные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '401':
          description: Пользователь не авторизирован
        '403':
          description: Недостаточно прав
        '500':
          description: Внутренняя ошибка сервера
      security:
        - jwt_bearer_auth: []
  /api/v2/users/login:
    post:
      tags:
        - auth
      summary: Аутентификация
      description: Аутентификация пользователя по логину и паролю
      operationId: handle_auth_v2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: true
      responses:
        '200':
          description: Пользователь успешно авторизирован
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Невалидные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Внутренняя ошибка сервера
  /api/v2/users/me:
    get:
      tags:
        - user
      summary: Получение данных пользователя
      description: Получение данных авторизированного пользователя
      operationId: handle_get_user_me_v2
      responses:
        '200':
          description: Пользователь успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithId'
        '401':
          description: Пользователь не авторизирован
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Внутренняя ошибка сервера
      security:
        - jwt_bearer_auth: []
  /api/v2/users/registr:
    post:
      tags:
        - auth
      summary: Регистрация
      description: Регистрация нового пользователя
      operationId: handle_reg_v2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegRequest'
        required: true
      responses:
        '204':
          description: Пользователь успешно зарегестрирован
        '400':
          description: Невалидные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '409':
          description: Пользователь с заданным email уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Внутренняя ошибка сервера
  /api/v2/users/{id}:
    get:
      tags:
        - user
      summary: Получение данных пользователя
      description: Получение данных пользователя по id
      operationId: handle_get_user_by_id_v2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        '200':
          description: Пользователь успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserWithId'
        '401':
          description: Пользователь не авторизирован
        '403':
          description: Недостаточно прав
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Внутренняя ошибка сервера
      security:
        - jwt_bearer_auth: []
    delete:
      tags:
        - user
      summary: Удаление пользователя
      description: Удаление пользователя по id
      operationId: handle_delete_user_by_id_v2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        '204':
          description: Пользователь успешно удален
        '401':
          description: Пользователь не авторизирован
        '403':
          description: Недостаточно прав
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Внутренняя ошибка сервера
      security:
        - jwt_bearer_auth: []
  /api/v2/users/{id}/passport:
    patch:
      tags:
        - user
        - auth
      summary: Подтверждение паспортных данных
      description: Подтверждение паспортных данных пользователя
      operationId: handle_passport_conf_v2
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
        required: true
      responses:
        '204':
          description: Пользователь успешно обновил паспортные данные
        '400':
          description: Невалидные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '401':
          description: Пользователь не авторизирован
        '403':
          description: Недостаточно прав
        '404':
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '409':
          description: Паспортные данные уже привязаны к другому пользователю
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Внутренняя ошибка сервера
      security:
        - jwt_bearer_auth: []
components:
  schemas:
    AuthRequest:
      type: object
      required:
        - email
        - pswd
      properties:
        email:
          type: string
          example: email@example.com
        pswd:
          type: string
          example: password
    AuthResponse:
      type: object
      required:
        - jwt
      properties:
        jwt:
          type: string
          example: jwt-example
    Car:
      type: object
      required:
        - owner_fio
        - gos_num
        - model
        - mark
        - color
        - year
        - vin
        - sts
        - pts
      properties:
        color:
          type: string
        gos_num:
          type: string
        mark:
          type: string
        model:
          type: string
        owner_fio:
          type: array
          items: false
          prefixItems:
            - type: string
            - type: string
            - type:
                - string
                - 'null'
        pts:
          $ref: '#/components/schemas/Document'
        sts:
          $ref: '#/components/schemas/Document'
        vin:
          type: string
        year:
          type: integer
          format: int32
          minimum: 0
    CarSearcherResponse:
      type: object
      required:
        - offset
        - cars
      properties:
        cars:
          type: array
          items:
            $ref: '#/components/schemas/Car'
          example: []
        offset:
          type: integer
          example: 0
          minimum: 0
    Document:
      type: object
      required:
        - serial
        - number
      properties:
        number:
          type: string
          example: '111111'
        serial:
          type: string
          example: '1111'
    Location:
      type: object
      required:
        - longitude
        - latitude
      properties:
        latitude:
          type: number
          format: double
          example: 53.9333
        longitude:
          type: number
          format: double
          example: 53.9222
    PointData:
      type: object
      required:
        - cords
      properties:
        cords:
          $ref: '#/components/schemas/Location'
        speed:
          type:
            - integer
            - 'null'
          format: int32
          example: 60
          minimum: 0
    RegRequest:
      type: object
      required:
        - firstname
        - surname
        - email
        - pswd
      properties:
        email:
          type: string
          example: email@example.com
        firstname:
          type: string
          example: firstname
        lastname:
          type:
            - string
            - 'null'
          example: lastname
        pswd:
          type: string
          example: password
        surname:
          type: string
          example: surname
    Role:
      type: string
      enum:
        - user
        - operator
        - audit
    RouteRequest:
      type: object
      required:
        - gos_num
        - date
      properties:
        date:
          type: string
          example: 01.01.2025
        gos_num:
          type: string
          example: А777МР77
    RouteResponse:
      type: object
      required:
        - route
      properties:
        route:
          type: array
          items:
            $ref: '#/components/schemas/PointData'
    SearchCarsRequest:
      type: object
      required:
        - passport
      properties:
        gos_num:
          type:
            - string
            - 'null'
          example: А*23**99
        lastname:
          type:
            - string
            - 'null'
          example: lastname
        limit:
          type:
            - integer
            - 'null'
          example: 100
        name:
          type:
            - string
            - 'null'
          example: name
        offset:
          type:
            - integer
            - 'null'
          example: 0
          minimum: 0
        passport:
          $ref: '#/components/schemas/Document'
        surname:
          type:
            - string
            - 'null'
          example: surname
    SearchTrackInfoByFilterRequest:
      type: object
      required:
        - passport
      properties:
        date:
          type:
            - string
            - 'null'
          example: 01.01.2025
        gos_num:
          type:
            - string
            - 'null'
          example: А*23**99
        lastname:
          type:
            - string
            - 'null'
          example: lastname
        limit:
          type:
            - integer
            - 'null'
          example: 100
        name:
          type:
            - string
            - 'null'
          example: name
        offset:
          type:
            - integer
            - 'null'
          example: 0
          minimum: 0
        passport:
          $ref: '#/components/schemas/Document'
        surname:
          type:
            - string
            - 'null'
          example: surname
    StatusResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          example: 0
        message:
          type: string
          example: OK
    TrackInfo:
      type: object
      required:
        - track_time
        - route_date
        - car
        - user
      properties:
        car:
          $ref: '#/components/schemas/Car'
        route_date:
          type: string
        track_time:
          type: string
        user:
          $ref: '#/components/schemas/User'
    TrackInfoSearcherResponse:
      type: object
      required:
        - offset
        - track_infos
      properties:
        offset:
          type: integer
          example: 0
          minimum: 0
        track_infos:
          type: array
          items:
            $ref: '#/components/schemas/TrackInfo'
          example: []
    User:
      type: object
      required:
        - name
        - surname
        - email
        - role
        - is_verified
      properties:
        email:
          type: string
          example: email@example.ru
        is_verified:
          type: boolean
          example: true
        lastname:
          type:
            - string
            - 'null'
          example: Ivanovich
        name:
          type: string
          example: Ivan
        passport:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/Document'
        role:
          $ref: '#/components/schemas/Role'
        surname:
          type: string
          example: Ivanov
    UserWithId:
      type: object
      required:
        - id
        - name
        - surname
        - email
        - role
        - is_verified
      properties:
        email:
          type: string
          example: email@example.ru
        id:
          type: integer
          example: 1
          minimum: 0
        is_verified:
          type: boolean
          example: true
        lastname:
          type:
            - string
            - 'null'
          example: Ivanovich
        name:
          type: string
          example: Ivan
        passport:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/Document'
        role:
          $ref: '#/components/schemas/Role'
        surname:
          type: string
          example: Ivanov
  securitySchemes:
    jwt_bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: route
    description: Получение маршрута
  - name: auth
    description: Авторизация
  - name: user
    description: Пользователь
  - name: search
    description: Поисковик
  - name: car
    description: Автомобили
  - name: track-info
    description: Информация об отслеживании
