[package]
name = "dependencies_container"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"

data_access = { path = "./../data_access"}
business_logic = { path = "./../business_logic" }
