[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
utoipa = { version = "5.3.1", features = ["axum_extras"] }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"