name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Setup env
      working-directory: ./backend
      run: |
        sed -i "s|PROJECT_ROOT=.*|PROJECT_ROOT=$GITHUB_WORKSPACE/backend|g" .env
        cat .env
    
    - name: Start Docker containers
      working-directory: ./backend
      run: |
        docker compose up -d

    - name: Load environment variables
      working-directory: ./backend
      run: |
        if [ -f .env ]; then
          export $(grep -v '^#' .env | xargs)
        else
          echo "Error: .env file not found"
          exit 1
        fi

    - name: Postgres data preparing
      working-directory: ./backend/db/sql_scripts/postgres
      run: |
        for script in tables.sql constraints.sql roles.sql procedure.sql functions.sql copy.sql; do
          if [ -f "$script" ]; then
            echo "Executing $script"
            docker exec -i postgres psql -h localhost -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB < "$script"
          else
            echo "Warning: $script not found"
          fi
        done
