[package]
name = "cameras"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
# tokio = { version = "1.20", features = ["full"] }

# models = { path = "./../../api/src/models" }
# data_access = { path = "./../../api/src/data_access"}